title: "OBRD : Hybrid Object Detection"
description: "Offline + Cloud Object Detection PWA using TensorFlow.js and Hugging Face"
theme: minima

exclude:
  - api-server/
  - node_modules/
  - package-lock.json
  - package.json
  - Gemfile
  - Gemfile.lock
  - .github/
  - venv/
  - .venv/

include:
  - manifest.json
  - service-worker.js
  - static/js/apiBridge.js

markdown: kramdown
plugins: []
