name: CI/CD for FastAPI Object Detection

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 1. Build and Test Job
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies and Run tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If you have unit tests, run them here
          # pytest 

  # 2. Build and Push Docker Image Job (Only runs if tests pass)
  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: your-docker-username/object-detection-api:latest

  # 3. Deployment Job (Deployment steps vary wildly by cloud/server)
  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Remote Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull your-docker-username/object-detection-api:latest
            docker stop my_app || true
            docker rm my_app || true
            docker run -d --name my_app -p 80:80 your-docker-username/object-detection-api:latest
            
